### ISSUE TITLE
Erreur lors de l'inscription d'un nouvel utilisateur

### ISSUE THREAD

**Issue by Realexx** [uha-fr/archiweb_2024_projets_gr04#16]
( ! ) Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicata du champ '660' pour la clef 'utilisateurs.PRIMARY' in \archiweb_2024_projets_gr04\src\Models\Model.php on line 118
( ! ) PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicata du champ '660' pour la clef 'utilisateurs.PRIMARY' in archiweb_2024_projets_gr04\src\Models\Model.php on line 118

Cela vient de la fonction uniqid() qui est utilisé pour générer un identifiant unique lors de l'inscription.

**Comment by TheoNicod** [comment]
Il faut mettre à jour la bdd que je viens de push
